version: '2'

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
  flask-app:
    build: ./flask_app
    container_name: flask
    ports:
      - 5000:5000
